language: ruby
rvm:
 - 3.2
script:
 - |
    ruby test.rb
    echo "${TRAVIS_BRANCH}"

    if [[ ! -z "${TRAVIS_TAG}" ]] ; then

      echo "Tag triggered ${TRAVIS_TAG}"
branches:
  only:
    - /^\d+\.\d+(\.\d+)?$/
